[2022-12-28T00:00:06.198+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.downloading_rates scheduled__2022-12-27T00:00:00+00:00 [queued]>
[2022-12-28T00:00:06.219+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.downloading_rates scheduled__2022-12-27T00:00:00+00:00 [queued]>
[2022-12-28T00:00:06.220+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-28T00:00:06.221+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 3
[2022-12-28T00:00:06.222+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-28T00:00:06.247+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): downloading_rates> on 2022-12-27 00:00:00+00:00
[2022-12-28T00:00:06.252+0000] {standard_task_runner.py:55} INFO - Started process 105 to run task
[2022-12-28T00:00:06.257+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'forex_data_pipeline', 'downloading_rates', 'scheduled__2022-12-27T00:00:00+00:00', '--job-id', '489', '--raw', '--subdir', 'DAGS_FOLDER/forex_data_pipeline.py', '--cfg-path', '/tmp/tmp48cunw7q']
[2022-12-28T00:00:06.259+0000] {standard_task_runner.py:83} INFO - Job 489: Subtask downloading_rates
[2022-12-28T00:00:06.355+0000] {task_command.py:389} INFO - Running <TaskInstance: forex_data_pipeline.downloading_rates scheduled__2022-12-27T00:00:00+00:00 [running]> on host b21115e7dff0
[2022-12-28T00:00:06.465+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=juanfelipehdezm@gmail.com
AIRFLOW_CTX_DAG_OWNER=felipehdez
AIRFLOW_CTX_DAG_ID=forex_data_pipeline
AIRFLOW_CTX_TASK_ID=downloading_rates
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-27T00:00:00+00:00
[2022-12-28T00:00:10.741+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/forex_data_pipeline.py", line 34, in download_rates
    data = json.loads(r.text)["Realtime Currency Exchange Rate"]
KeyError: 'Realtime Currency Exchange Rate'
[2022-12-28T00:00:10.757+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=forex_data_pipeline, task_id=downloading_rates, execution_date=20221227T000000, start_date=20221228T000006, end_date=20221228T000010
[2022-12-28T00:00:10.772+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 489 for task downloading_rates ('Realtime Currency Exchange Rate'; 105)
[2022-12-28T00:00:10.817+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-28T00:00:10.845+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
